### ISSUE TITLE
Could you please describe why to use AngularJS Helper?

### ISSUE THREAD

**Issue by wachara-yanu** [JanVanBraeckel/Building-Strongly-Typed-AngularJS-Apps-with-ASP.NET-MVC-5#1]

**Comment by JanVanBraeckel** [comment]
Hi, this code was written while following a Pluralsight class. It's been a while since I followed the class so it's hard to recall what all of it does :)

You can find the course here if you're interested:
https://app.pluralsight.com/library/courses/building-strongly-typed-angularjs-apps-aspdotnet-mvc5/table-of-contents

**Comment by wachara-yanu** [comment]
@JanVanBraeckel nice course.
